---

# Contains only disabled cops.
# Please document (with comments) why a cop is disabled.

Metrics/ClassLength: # Not useful
  Enabled: false

Naming/VariableNumber: # Less readable
  Enabled: false

Rails/Presence: # Less readable
  Enabled: false

Rails/UniqueValidationWithoutIndex: # broken
  Enabled: false

Rails/UnusedIgnoredColumns: # Not practical
  Enabled: false

Rake/Desc: # Not practical
  Enabled: false

RSpec/ExampleLength: # Not practical
  Enabled: false

RSpec/MultipleExpectations: # Not practical
  Enabled: false

Style/ClassAndModuleChildren: # Decide what we want
  Enabled: false

Style/Documentation: # No, just no
  Enabled: false
